gText_Birch_Welcome::
	.string "Hey there kid!\p"
	.string "You're even hotter than I\n"
	.string "expected!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "Everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "But you can call me\n"
	.string "DADDY.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as passionate lovers.\p"
	.string "And sometimes, we make them\n"
	.string "kill each other for fun!\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many,\n"
	.string "many, many, many, many, many\1"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\p"
	.string "And chatting with minors.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, what's under those pants?$"

gText_Birch_BoyOrGirl::
	.string "Do you have a PENIS\n"
	.string "Or a VAGINA?$"

gText_Birch_WhatsYourName::
	.string "That's hot.\n"
	.string "What's your name, cutie?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Fuck, yeah!\p"
	.string "You're {PLAYER}{KUN} who's moving next\n"
	.string "door to me in LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Oh shit, I think my wife got home\n"
	.string "home early.\p"
	.string "She can't find me like this again!\p"
	.string "How the hell do I turn this\n"
	.string "fucking thing off...\p"
	.string "$"
